### PR TITLE
Rework ws

### PR DESCRIPTION
**Pull request by andrej-sajenko**
Hey guys,

I think we should avoid issues in the future by not using the JavaScala conversions.
Whenever possible use the Scala collection api instead of util.Map|Set|List.
Moreover, use MediaType constants instead of strings and prefer val against var.

Adressed points
* Moved DB Config into application.conf
* Use Spring JdbcTemplate for database connections
* create default database for WS
* Removed a lot of JavaConversions
* Add a Spring Boot JdbcTemplate Wrapper to avoid Type issues with java types.
* Replaced some null values by using the Scala Option Type
* Added CAS-Library (old one is still in the project, but markt as deprecated.)
* Create DB-Schema on startup if none exists (checks if the course table exists)

@bees4ever Can you check if everything you have done still works?

### CODE REVIEW

**Comment by andrej-sajenko** [comment]
Hmm, know I know why you had to use the java.util.Map as return types in the RestControllers.
Fix is on the way.

**Comment by andrej-sajenko** [comment]
@bees4ever I have changed the default database from `db1` to `submissionchecker.
Maybe this is the reason for the error. However, the whole schema needs to be created before using any service that requires a working database. Since I do not know the schema I was not able to test it.
In future, if the systems starts up it should test if the schema was already created and if not create everything it needs.

**Comment by bees4ever** [comment]
@andrej-sajenko I also have a schema called `submissionchecker`. I analyzed the line 28 again and saw, that `jdbc` is null, so no queries can be performed.
I looked further and tried to initialize `jdbc` by hand. So I come up with:
```
val ds = DataSourceBuilder.create().username("username")
      .password("password")
      .url("jdbc:mysql://localhost:3308/submissionchecker")
      .driverClassName("com.mysql.cj.jdbc.Driver")
      .build()
    val jdbc2 = new JdbcTemplate(ds)
    jdbc2.query(sql, rowMapper, args).asScala.toList
```
which worked somehow. But, the schema "submissionchecker" which this Connector is accessing has no data, which is weird. After this I modified the `update` method and saw, that something more is wrong. Even if enough arguments are given the line:
`jdbc2.update(sql, args)` crashed with 
````
java.sql.SQLException: No value specified for parameter 2
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.13.jar:8.0.13]
````
I don't know what to do, so I send you a mail with a complete dump of the database, maybe you can test yourself? Or what can I do?

**Comment by andrej-sajenko** [comment]
> I don't know what to do, so I send you a mail with a complete dump of the database, maybe you can test yourself? Or what can I do?

Sure, send me the dump and I will fix it this evening.

**Comment by andrej-sajenko** [comment]
@bees4ever Fixed the SQLExceptions and added the CAS-Changes.

**Comment by bees4ever** [comment]
@andrej-sajenko Now, a login request or other requests are blocked by the CAS. I don't know, if this expected? 

bildschirmfoto 2018-11-23 um 19 04 55

**Comment by andrej-sajenko** [comment]
included in #59

**Pull request closed without merging**
